frontendweb:
  image: nginx:1.9
  ports:
    - "2086:80"
  volumes:
    - frontend:/usr/share/nginx/html
backendweb:
  image: nginx:1.9
  ports:
    - "2095:80"
  volumes:
    - backend:/var/www/nebula
    - backend/configuration/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
   - backendphp
backendphp:
  build: backend/configuration
  command: php-fpm --allow-to-run-as-root
  volumes:
    - backend:/var/www/nebula
    - backend/configuration/php-fpm.conf:/usr/local/etc/php-fpm.conf
  links:
    - mysql
testing:
  image: php:5.6-cli
  volumes:
    - testing:/usr/src/nebula
  links:
    - frontendweb
    - backendweb
mysql:
  image: mariadb:10.0
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=nebula
    - MYSQL_PASSWORD=nebula
    - MYSQL_DATABASE=nebula
